# your domain
domain: huoche.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files: 
  # use local file
  - ./config/source.yaml
  # use web file
  - https://raw.githubusercontent.com/shope1860/test/master/config/source.yaml
